// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQklt-kTfTM8CZQvPPJslfr7P6bpnuo8',
    appId: '1:190341061745:android:e28f03d103fc9de4820fd0',
    messagingSenderId: '190341061745',
    projectId: 'clippicreview',
    databaseURL: 'https://clippicreview.firebaseio.com',
    storageBucket: 'clippicreview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGUJezaBC33YNFcwbVSfc1NQwSokoMsxI',
    appId: '1:190341061745:ios:6a6bbf33b058d0b5820fd0',
    messagingSenderId: '190341061745',
    projectId: 'clippicreview',
    databaseURL: 'https://clippicreview.firebaseio.com',
    storageBucket: 'clippicreview.appspot.com',
    androidClientId: '190341061745-u59bekic5vg0l59mgh7u5a4m1ea2hmgj.apps.googleusercontent.com',
    iosClientId: '190341061745-417fs03bafcvav6c7g1ecn9v39omf08q.apps.googleusercontent.com',
    iosBundleId: 'com.maranta4.cpruser.ios',
  );
}
